name = "mevzuatrehberi"
main = "worker/index.js"
compatibility_date = "2026-07-20"

[vars]
APPLE_TEAM_ID = "4L6B4S88G6"
APPLE_KEY_ID = "WJ94KH56BZ"
APPLE_CLIENT_ID = "com.isgmevzuatrehberi.web"
APPLE_REDIRECT_URI = "https://www.isg-mevzuat-rehberi.com.tr/api/auth/apple/callback"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "mevzuatrehberi"
database_id = "f826a842-a4d9-4f51-a623-77913c985445"
migrations_dir = "worker/migrations"
